--liquibase formatted sql

--changeset MarkusSaw:create-students-table

SET search_path TO managemt_system;

CREATE TABLE course (
     id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     name VARCHAR(255),
     description VARCHAR(255),
     PRIMARY KEY (id)
);