--liquibase formatted sql

--changeset MarkusSaw:create-students-table

SET search_path TO managemt_system;

CREATE TABLE timesheet (
      id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      group_name VARCHAR(255),
      teacher VARCHAR(255),
      course VARCHAR(255),
      date_of_the_lesson VARCHAR(255),
      PRIMARY KEY (id)
);